//------------------------------------------------------------------------------
// <auto-generated>
//     Archivo de recursos generado por Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GestionEmpleados_DatabaseFirst.Properties
{
    internal class Resources
    {
        private Resources() { }
    }
}
