//------------------------------------------------------------------------------
// <auto-generated>
//     Clase de entidad generada desde la tabla Empleados de SQL Server.
//     Se conserva separada de las clases de herencia para respetar Database First.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEmpleados_DatabaseFirst.Modelos
{
    //Representa un registro de la tabla Empleados.
    public partial class EmpleadoBD
    {
        public int IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public decimal Sueldo { get; set; }
        public string Cargo { get; set; }
        public string TipoEmpleado { get; set; }
    }
}
