//------------------------------------------------------------------------------
// <auto-generated>
//     Archivo equivalente al contexto generado por el modelo Database First.
//     Si se actualiza el modelo desde Visual Studio, este archivo puede regenerarse.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEmpleados_DatabaseFirst.Modelos
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    //Contexto de Entity Framework generado a partir de la base de datos.
    public partial class DB_GestionEmpleadosEntities : DbContext
    {
        public DB_GestionEmpleadosEntities()
            : base("name=DB_GestionEmpleadosEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //Evita que Entity Framework intente trabajar como Code First.
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<EmpleadoBD> Empleados { get; set; }
    }
}
